apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: axiom-portal

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: axiom-portal
  managed-by: kustomize

images:
  - name: axiom-portal
    newName: your-registry/axiom-portal
    newTag: latest
