apiVersion: v1
kind: Service
metadata:
  name: axiom-portal-service
  namespace: axiom-portal
  labels:
    app: axiom-portal
spec:
  type: LoadBalancer
  selector:
    app: axiom-portal
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
